# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[(b'PRD', b'Farmer'), (b'BUY', b'Buyer')], default=b'BUY', max_length=3),
        ),
    ]
