# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[(b'PRDR', b'Farmer'), (b'BUYR', b'Buyer'), (b'PPRDR', b'Pro Farmer'), (b'PBUYR', b'Pro Buyer')], default=b'BUYR', max_length=3),
        ),
    ]
