# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160915_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[(b'PRD', b'Farmer'), (b'BUY', b'Buyer'), (b'PRO', b'Pro Account')], default=b'BUY', max_length=3),
        ),
    ]
