# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160915_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='follow',
            new_name='follows',
        ),
    ]
