# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0002_auto_20160913_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('images', models.ImageField(blank=True, upload_to='products')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Small Stock', (('Goats', 'Goats'), ('Sheep', 'Sheep'))), ('Cattle', 'Cattle'), ('Poultry', (('Chicken', 'Chicken'), ('Geese', 'Geese'))), ('Fresh Produce', (('Spinach', 'Spinach'), ('Cabbage', 'Cabbage')))], default='None', max_length=3)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
