# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Small Stock', (('Goats', 'Goats'), ('Sheep', 'Sheep'))), ('Cattle', 'Cattle'), ('Poultry', (('Chicken', 'Chicken'), ('Geese', 'Geese'))), ('Fresh Produce', (('Spinach', 'Spinach'), ('Cabbage', 'Cabbage')))], default='None', max_length=255),
        ),
    ]
