# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_auto_20160913_1342'),
        ('products', '0003_auto_20160915_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Farm'),
        ),
    ]
