# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160825_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
