# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Livestock', (('Small Stock', (('Goats', 'Goats'), ('Sheep', 'Sheep'), ('Cattle', 'Cattle'))), ('Large Animals', (('Cattle', 'Cattle'),)), ('Game', (('Impala', 'Impala'),)), ('Poultry', (('Chicken', 'Chicken'), ('Geese', 'Geese'))))), ('Crops', ('Fresh Produce', (('Spinach', 'Spinach'), ('Cabbage', 'Cabbage'))))], default='None', max_length=255),
        ),
    ]
