# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20160913_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
