# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='location',
        ),
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
    ]
